# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nikhil and Charlotte
tagline:          'Changmukh'
description:      'Two kids, one ring.'
url:              http://nikhilde.github.io/changmukh
baseurl:          /

author:
  name:           'Nikhil Deshmukh'
  url:            https://twitter.com/nikhildes

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
